package com.mit.kinatwabusapplication.navigation

const val ROUTE_INDEX="Index"
const val ROUTE_REGISTER="Register"
const val ROUTE_LOGIN="Login"
const val ROUTE_HOME="Home"
const val ROUTE_BOOKING="Booking"
const val ROUTE_ABOUT="About"
const val ROUTE_CONTACT_US="Contact_us"
const val ROUTE_MOUNTAIN_BIKES="Mountain_Bikes"
const val ROUTE_CITY_BIKES="City_Bikes"
const val ROUTE_KID_BIKES="Kid_Bikes"
const val ROUTE_CHECK_OUT="Done"
const val ROUTE_DETAILS="Details"
const val ROUTE_SPLASH="Splash"